version: 2
executorType: docker
containerInfo:
  - image: node:latest
stages:
  build:
    workDir: /home/ubuntu/demo-react-working
    steps:
      - type: checkout
      - type: add-ssh-keys
      - type: shell
        name: Pre-Dep
        command: mkdir /home/ubuntu/artifacts
      - type: shell
        name: Install Dependencies
        command: npm install
      - type: shell
        name: NPM Test
        command: npm test
      - type: artifacts-store
        path: /home/ubuntu/artifacts
      - type: deploy
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            # Install Heroku fingerprint
            echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

            git config --global push.default simple
            git push -f git@heroku.com:cci-demo-react.git
          fi
